version: '1'

services:
  baidunetdisk-vnc:
    image: emuqi/baidunetdisk-arm64-vnc:latest
    container_name: baidunetdisk-vnc
    environment:
      - USER_ID=1000
      - GROUP_ID=1000 
    volumes:
      - ${PWD}/bdnetdisk-config:/config
      - ${PWD}/downloads:/config/baidunetdiskdownload
    ports:
      - "5800:5800" # noVNC 端口 按需要修改冒号前面端口
      - "5900:5900" # VNC 端口 按需要修改冒号前面端口
    restart: unless-stopped